### ISSUE TITLE
Error in index?

### ISSUE THREAD

**Issue by kennyyeo13** [julianeweller/mg2sc#1]
Hi Juliane, 

I received this error when I run the file, I was wondering if I have to generate the index file for the original bam file?

The code can generate everything but the counts.

This is my code

python scMeG-kraken.py --input /hpcfs/users/a1811332/batch3outputV3/${s}_sorted.bam --outdir /hpcfs/users/a1811332/batch3outputV3/output/${s}_scMeG --DBpath /hpcfs/users/a1811332/kenny_supercomputer/Kraken/KrakenDB/new --threads 32 --prefix ${s}_output --v info

Here's the error:

INFO:root:Started the run.
INFO:root:Input bamfile: /hpcfs/users/a1811332/batch3outputV3/SRR15488195_sorted.bam
INFO:root:Output krakenfile: /hpcfs/users/a1811332/batch3outputV3/output/SRR15488195_scMeG/SRR15488195_output_output.kraken
INFO:root:Threads used: 32
INFO:root:Unmapped reads were extracted and saved to /hpcfs/users/a1811332/batch3outputV3/output/SRR15488195_scMeG/SRR15488195_output_unmapped.bam
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 11638182 reads
INFO:root:FASTQ generated and saved to /hpcfs/users/a1811332/batch3outputV3/output/SRR15488195_scMeG/SRR15488195_output_unmapped.fq
Loading database information... done.
11638182 sequences (1140.54 Mbp) processed in 2.413s (289353.3 Kseq/m, 28356.63 Mbp/m).
  2788388 sequences classified (23.96%)
  8849794 sequences unclassified (76.04%)
INFO:root:Kraken2 finished running, krakenoutput saved to /hpcfs/users/a1811332/batch3outputV3/output/SRR15488195_scMeG/SRR15488195_output_output.kraken
[E::idx_find_and_load] Could not retrieve index file for '/hpcfs/users/a1811332/batch3outputV3/output/SRR15488195_scMeG/SRR15488195_output_unmapped.bam'
INFO:root:total reads: 11638182, skipped reads: 11638182
Traceback (most recent call last):
  File "/hpcfs/users/a1811332/mg2sc/src/scMeG-kraken.py", line 82, in <module>
    mg2sc(bamfile_out, krakenoutfile, args.dbfile, args.outdir)
  File "/hpcfs/users/a1811332/mg2sc/src/k2sc.py", line 31, in mg2sc
    sparsematrix = csr_matrix((vals, (rows, cols)))
  File "/gpfs/apps/icl/software/Anaconda3/2023.03/lib/python3.10/site-packages/scipy/sparse/_compressed.py", line 53, in __init__
    self._coo_container(arg1, shape=shape, dtype=dtype)
  File "/gpfs/apps/icl/software/Anaconda3/2023.03/lib/python3.10/site-packages/scipy/sparse/_coo.py", line 148, in __init__
    raise ValueError('cannot infer dimensions from zero '
ValueError: cannot infer dimensions from zero sized index arrays

**Comment by ktpolanski** [comment]
The key to what is happening is in the line below:
```
INFO:root:total reads: 11638182, skipped reads: 11638182
```
Looking at the source code, there are two conditions for a line being skipped - either a mismatch in read name between the BAM and kraken (but that should produce a warning), or an absence of `CB`/`UB` tags in the read. Does your input BAM have `CB`/`UB` tags?

**Comment by kennyyeo13** [comment]
Hi ktpolanski, thank you for the quick reply. I am a beginner in bioinformatics so I might be asking some really basic questions. I ran STARsolo to get the unsorted bam files, then run samtools to sort the bam files before running python scMeG-kraken.py. I think there's something wrong on my STARsolo code, do you have any recommendations here? 

Thank you for the help


**these is the fastq file of my bam file inputted into scMeG, which does not have any barcode information.**
@SRR15488197.387945
ACAAAAATTGGCCGGGCGTGGTGACACAGGTCTGTAATCCCAGGTATGCAGAACGCTGAGGCACAAGAATCGCTTGAACCTGGGAGACAGAAATTGCA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@SRR15488197.387946
CTCACCACAACCTCTGCCTCCCGGGTCCAAGCCATTCTCCTGCCTACCCAGTAGCTAGGATTACAGGCACCCAGTACCACGCCTGGCTAATTTTTTAT
+
FFF,FF:F,:FF,F,FFF,FFFFFF,FFFFFFF,FFF:FFFFFF:,FFF,F,:FF,,FF,,F,F,FFFFFFF:F:,FFFFFFF,FFFF:F:::F:FFF
@SRR15488197.387947
CTGAGATCAGAGTCCTACAGTGGCTGTCACGCAGCCACCAGGTCATCTCCTTTCATCCCCACCCCAAGGCGCTGGCTGTGACTCTGCTTCCTGCACTG
(base) [a1811332@p2-log-2 batch3outputV3]$ head SRR15488197_sorted.fastq  
@SRR15488197.86956784
GCCCCTGTAGGCCAAGGCGCCAGGCAGGACGACAGCAGCAGCAGCGCGTCTCCTTCAGTTACATGCAGACAACAGGGGCCAGAAGATGAACAATGGCC
+
FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFF
@SRR15488197.94216006
GCAGTGGTATCAACGCAGAGTACATGGGCGATGGCACCTCCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAAT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@SRR15488197.19218904
AACGGCACACCAATCAATAAAGAACTGAGCAGAAACCAACAGTGTGCTTTTAATAAAGGATCTCTAGCTGTGCAGGAAAAAAAAAAAAAAAAAAAAAA




**and Below are my codes:**

for s in ${samples[*]}
do
/hpcfs/users/a1811332/STAR-2.7.10b/bin/Linux_x86_64_static/STAR --runThreadN 40 --genomeDir /hpcfs/users/a1811332/STAR-2.7.10b/refdata-gex-GRCh38-2020-A/star --readFilesIn ${s}_2.fastq ${s}_1.fastq --soloType CB_UMI_Simple --soloCBwhitelist /hpcfs/users/a1811332/STAR-2.7.10b/V3.txt --outReadsUnmapped Fastx --soloUMIlen 12 --outSAMtype BAM Unsorted --outSAMunmapped Within --outFileNamePrefix /hpcfs/users/a1811332/batch3outputV3/${s} 
done

for s in ${samplebatch1[*]}
do
cd /hpcfs/users/a1811332/batch3outputV3
samtools sort ${s}Aligned.out.bam -o ${s}_sorted.bam
echo "Sorted ${s}"
done

for s in ${samplebatch1[*]}
do
cd /hpcfs/users/a1811332/mg2sc/src
python scMeG-kraken.py --input /hpcfs/users/a1811332/batch3outputV3/${s}_sorted.bam --outdir /hpcfs/users/a1811332/batch3outputV3/output / --DBpath /hpcfs/users/a1811332/kenny_supercomputer/Kraken/KrakenDB/new --threads 32 --prefix ${s}_output -v
done

**Comment by ktpolanski** [comment]
I'd recommend running starsolo with the following two parameters added/altered from your command:
```bash
--outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM
--outSAMtype BAM SortedByCoordinate
```
As per the official starsolo docs ("BAM tags" section [here](https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md)), you need to sort the BAM within starsolo to store `CB`/`UB` successfully. Those tags are then used by Juliane's script.

Since you'll be sorting the BAM at the starsolo level, you won't need to run the samtools sort anymore.

**Comment by kennyyeo13** [comment]
Hi ktpolanski, 

Thanks for your help! I'll close this issue for now. 

Kind regards
Kenny
